apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers: 
      - name: nodeapp
        image: vijayramdoc/nodeapp-deployment1:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: LB
spec:
  selector:
    app: nodeapp
  type : LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort : 30000
